version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:3000'
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    depends_on:
      - api-server
    networks:
      - react-app
  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8090:7000'
    volumes:
      - ./backend:/app/backend
      - ./backend/node_modules:/app/backend/node_modules
    depends_on:
      - mysql
    networks:
      - react-app
  mysql:
    image: mysql:8.0.28
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./backend/db:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    networks:
      - react-app
networks:
  react-app:
    driver: bridge
