name: Deploy Frontend

on:
  push:
    branches: [main, ui]

jobs:
  on_push_deploy:
    runs-on: self-hosted
    steps:
      - name: Action Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      # - name: Testing...
      #   run: npm test
      - name: Build Docker Container
        run: docker-compose up -d
